// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RulesEngine.Infrastructure.Persistence;

#nullable disable

namespace RulesEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RulesEngineEditorDbContext))]
    partial class RulesEngineEditorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RulesEngine.Infrastructure.Persistence.Entities.ExecutionStateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("text")
                        .HasColumnName("ErrorJson");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExecutedAtUtc");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDryRun");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ResultJson");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("boolean")
                        .HasColumnName("WasSuccessful");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id")
                        .HasName("PK_rule_execution_states");

                    b.ToTable("rule_execution_states", (string)null);
                });

            modelBuilder.Entity("RulesEngine.Infrastructure.Persistence.Entities.RuleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset?>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EffectiveFromUtc");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EffectiveToUtc");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("Expression")
                        .UseCollation("pg_catalog.\"default\"");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Name")
                        .UseCollation("pg_catalog.\"default\"");

                    b.Property<string>("RuleJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RuleJson")
                        .UseCollation("pg_catalog.\"default\"");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("Version");

                    b.HasKey("Id")
                        .HasName("PK_rules");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("RulesEngine.Infrastructure.Persistence.Entities.WorkflowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("Version");

                    b.Property<DateTimeOffset?>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EffectiveFromUtc");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EffectiveToUtc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Name");

                    b.HasKey("Id", "Version")
                        .HasName("PK_workflows");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("UX_workflows_Id_Active")
                        .HasFilter("\"IsActive\"");

                    b.HasIndex("Id", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_workflows_Id_Version");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("RulesEngine.Infrastructure.Persistence.Entities.WorkflowEntity", b =>
                {
                    b.OwnsOne("RulesEngine.Infrastructure.Persistence.Entities.WorkflowDefinitionEntity", "Definition", b1 =>
                        {
                            b1.Property<Guid>("WorkflowEntityId");

                            b1.Property<int>("WorkflowEntityVersion");

                            b1.Property<string>("Expression")
                                .IsRequired()
                                .HasJsonPropertyName("Expression");

                            b1.Property<string>("RuleJson")
                                .IsRequired()
                                .HasJsonPropertyName("RuleJson");

                            b1.HasKey("WorkflowEntityId", "WorkflowEntityVersion");

                            b1.ToTable("workflows");

                            b1
                                .ToJson("Definition")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowEntityId", "WorkflowEntityVersion");
                        });

                    b.Navigation("Definition")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
