<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="..\..\..\Build\Blazorise.props" />

  <PropertyGroup>
    <PackageTags>blazorise blazor components icons lucide</PackageTags>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Blazorise\Blazorise.csproj" />
  </ItemGroup>

</Project>